#Secret key generated by #OPEN SSL: Exit your virtual enviroment and execute openssl rand -hex 32
import os

JWT_SECRET_KEY = "761cf03008586a74f46d5bb566f6b2b9cd17f60ea37586c39c7a0f38c2cf0f75"
JWT_ALGORITHM = "HS256"
JWT_EXPIRATION_TIME_MINUTES = 60 *24*5
TOKEN_DESCRIPTION = (
    "It checks username and password if they are true, it returns JWT token to you."
)
TOKEN_SUMMARY = "It returns JWT token."

ISBN_DESCRIPTION = "It is unique identifier for books"
DB_HOST= "localhost"
DB_USER= "admin"
DB_NAME= "bookstore"
DB_PASSWORD= "admin"
DB_URL=f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}/{DB_NAME}"

UPLOAD_PHOTO_APIKEY = "a9463714a003ae92c5e347ccf7b7dbff"
UPLOAD_PHOTO_URL = f"https://api.imgbb.com/1/upload?key={UPLOAD_PHOTO_APIKEY}"

REDIS_URL = "redis://localhost"
#REDIS_URL_PRODUCTION = "redis://167.71.12.16"
#
#
# TESTING = False
# IS_LOAD_TEST = False
# IS_PRODUCTION = True if os.environ["PRODUCTION"] == "true" else False
#
# TEST_DB_HOST = "localhost"
# TEST_DB_USER = "test"
# TEST_DB_PASSWORD = "test"
# TEST_DB_NAME = "test"
# TEST_DB_URL = (
#     f"postgresql://{TEST_DB_USER}:{TEST_DB_PASSWORD}@{TEST_DB_HOST}/{TEST_DB_NAME}"
# )
#
#
# TEST_REDIS_URL = "redis://localhost"
#
# JWT_EXPIRED_MSG = "Your JWT token is expired! Renew the JWT token!"
# JWT_INVALID_MSG = "Invalid JWT token!"
# TOKEN_INVALID_CREDENTIALS_MSG = "Invalid username, password match !"
# JWT_WRONG_ROLE = "Unauthorized role!"