#Secret key generated by #OPEN SSL: Exit your virtual enviroment and execute openssl rand -hex 32
JWT_SECRET_KEY = "761cf03008586a74f46d5bb566f6b2b9cd17f60ea37586c39c7a0f38c2cf0f75"
JWT_ALGORITHM = "HS256"
JWT_EXPIRATION_TIME_MINUTES = 60 *24*5
TOKEN_DESCRIPTION = (
    "It checks username and password if they are true, it returns JWT token to you."
)
TOKEN_SUMMARY = "It returns JWT token."

ISBN_DESCRIPTION = "It is unique identifier for books"